### ISSUE TITLE
Pointer to code for generating HPT confidence intervals

### ISSUE THREAD

**Issue by allrtaken** [faster-cpython/benchmarking-public#39]
Hello,

I am interested in looking at the code for generating the HPT-based confidence levels. I searched Tools/scripts/summarize_stats.py in the CPython repo, but couldn't seem to find it. Can you please point me in the right direction? (Hope this is the right forum for this question) 

Thanks!
Aditya

**Comment by Fidget-Spinner** [comment]
I think it's here https://github.com/faster-cpython/bench_runner/blob/main/bench_runner/hpt.py

**Comment by allrtaken** [comment]
Thank you!
